# Generated by Django 4.1.7 on 2023-03-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('language', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
