# Generated by Django 4.1.7 on 2023-03-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myflixapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='myflixapi.genre'),
        ),
    ]
