# Generated by Django 4.1.7 on 2023-04-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myflixapi', '0002_rename_genre_id_genre_external_genre_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
